agregadas validaciones a rutas + modificado middleware para checkear …
luisparedes29/Nomina_Backend pull request #32
Opened 2023-11-11 05:10 UTC by gabrielcalderon16

**Contexto:** Los endpoints de la API no estaban validados, por lo cual se creo un sistema de roles tal cual se ideo en Telegram

**Roles:**
"super-admin": Es DIOS (pero se utiliza para modificar items muy criticos, como crear y eliminar empresas)
"admin": (se requiere para modificar items no tan criticos)
"user": (se requiere para el resto de rutas, mas que todo las que solo consultan informacion)

**Nota:**
Hay que enviar en cada consulta a cualquier endpoint el JWT y el rol actual (menos en el login y registro).

2023-11-12 20:23 UTC, Avendaosander requested changes
- Muchas autenticaciones estan mal

2023-11-14 01:18 UTC, gabrielcalderon16 commented
> * Muchas autenticaciones estan mal

Podrias ser mas especifico?

2023-11-14 01:30 UTC, Avendaosander commented
> > * Muchas autenticaciones estan mal
> 
> Podrias ser mas especifico?

Por ejemplo:
Ver una empresa, ver todas las empresas y crear una empresa solo tiene permiso a estas rutas un `superAdmin`.

Debes conocer los permisos a las distintas funciones, debes conocer tu proyecto!

2023-11-14 02:29 UTC, gabrielcalderon16 commented
> > > * Muchas autenticaciones estan mal
> > 
> > 
> > Podrias ser mas especifico?
> 
> Por ejemplo: Ver una empresa, ver todas las empresas y crear una empresa solo tiene permiso a estas rutas un `superAdmin`.
> 
> Debes conocer los permisos a las distintas funciones, debes conocer tu proyecto!

Lo siento pero los permisos para cada ruta no se definieron anteriormente como para que digas "debes conocer tu proyecto", en el telegram se habló solo de que el super admin era el que podria manipular las empresas, lo cual a mi entender es crear (POST) y editar (PUT), mas no leer o buscar (GET)

2023-11-16 20:01 UTC, st1nkyd00d requested changes
Asegurar que la autentación en las rutas sea la siguiente

- Agregar autenticacion a las rutas:
  * superAdmin:
    ~ Crear empresa
    ~ Ver empresas.
    ~ Editar empresa
    ~ Eliminar empresa
  * superAdmin, admin:
    ~ Ver una empresa
    ~ Register
    ~ Ver usuarios
    ~ Editar usuario
    ~ Eliminar usuario
  * admin:
    ~ Crear departamento
    ~ Editar departamento
    ~ Eliminar departamento
  * admin, user:
    ~ Ver departamentos
    ~ Ver empleados
    ~ Ver un empleado
    ~ Crear empleado
    ~ Editar empleado
    ~ Eliminar empleado
    ~ Ver percepciones de un empleado
    ~ Ver una percepcion
    ~ Crear percepcion
    ~ Editar percepcion
    ~ Eliminar percepcion
    ~ Ver deducciones de un empleado
    ~ Ver una deduccion
    ~ Crear deduccion
    ~ Editar deduccion
    ~ Eliminar deduccion
    ~ Crear nomina
    ~ Ver nominas
    ~ Ver una nomina
    ~ Editar estado de nomina

Por otra parte, no hacía falta modificar el middleware de "checkRole". De todos modos, para no descartarlo, se puede testear para verificar que funcione bien una vez actualizados los roles definidos en la lista anterior

2023-11-19 22:33 UTC, gabrielcalderon16 commented
Las modificaciones de `checkRole` tienes razon que no pueden parecer necesarias, pero al tratarse de una logica que optimiza codigo, es decir: 

 En vez de utilizar el middleware 3 veces para asegurarse que un usuario tenga el rol `user` (al cual los administradores y super-administrador, por el prestigio de sus roles tambien pueden acceder)
 ```
    checkRole("super-admin"),
    checkRole("admin"),
    checkRole("user"),
 ```
 Simplemente con una sola validacion se asegura que el super admin o el admin pueda acceder a `user`
  ```
    checkRole("user"),
 ```
  
  Por ello, considero adecuado mantener el codigo nuevo en `checkRole`

2023-11-19 22:46 UTC, gabrielcalderon16 commented
Se hicieron las modificaciones sugeridas, las rutas desarrolladas a día de hoy quedaron de la siguiente forma:

```
Agregar autenticacion a las rutas:
superAdmin:
~ Crear empresa (listo)
~ Ver empresas. (listo)
superAdmin, admin:
~ Ver una empresa (listo)
~ Register (listo)
~ Ver usuarios (listo)
admin:
~ Crear departamento (listo)
~ Editar departamento (listo)
~ Eliminar departamento (listo)
admin, user:
~ Ver departamentos (listo)
~ Ver empleados (listo)
~ Ver un empleado (listo)
~ Crear empleado (listo)
~ Editar empleado (listo)
~ Eliminar empleado (listo)
~ Ver percepciones (listo)
~ Crear percepcion (listo)
~ Editar percepcion (listo)
- Ver deducciones (listo)
~ Crear deduccion (listo)
~ Editar deduccion (listo)
~ Eliminar deduccion (listo)
~ Crear nomina (listo)
~ Ver nominas (listo)
~ Ver una nomina (listo)
```

2023-11-19 23:52 UTC, st1nkyd00d approved these changes
Voy a aprobar el pull para probarlo desde tu rama. Si todo está bien, te aviso para que hagas PR a `dev`

2023-11-19 23:52 UTC, luisparedes29 approved these changes
Aprobado para poder probar en tu rama, actualiza el codigo que ya hay cosas nuevas en algunas de las rutas

2023-11-20 01:33 UTC, gabrielcalderon16 commented
> Aprobado para poder probar en tu rama, actualiza el codigo que ya hay cosas nuevas en algunas de las rutas

Hay nuevos cambios en la rama dev?, si es asi en ese caso procedo ahorita a hacer el fetch y subir las nuevas validaciones

2023-11-20 01:45 UTC, gabrielcalderon16 commented
> > Aprobado para poder probar en tu rama, actualiza el codigo que ya hay cosas nuevas en algunas de las rutas
> 
> Hay nuevos cambios en la rama dev?, si es asi en ese caso procedo ahorita a hacer el fetch y subir las nuevas validaciones

Listo los cambios.

2023-11-20 02:20 UTC, gabrielcalderon16 commented
Hare merge para enviar estos cambios a la rama `dev`, por que actualmente están en `gabriel_dev`

2023-11-20 02:20 UTC, merged